### ISSUE TITLE
Unable to deploy entry point for a new test community

### ISSUE THREAD

**Issue by xdamman** [citizenwallet/smartcontracts#18]
I was trying to deploy a new community on Base Sepolia (testnet), but I ran into this issue:

Problem is probably here:
https://github.com/citizenwallet/smartcontracts/blob/d98c1ab51d7526c65702e84edc6954ed30be709c/scripts/deploy-community-entrypoint.ts#L77-L81

Has something changed for deploying a profile contract?

Here is the log:
```
🏃🏻‍♂️ Running...

Custom profile contract address (leave empty if you want to create a new one): 




⚙️ deploying Profile...
Error: types/values length mismatch (count={"types":1,"values":0}, value={"types":[{"name":"_owner","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true}],"values":[]}, code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at AbiCoder.encode (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:101:20)
    at Interface._encodeParams (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@ethersproject/abi/src.ts/interface.ts:323:31)
    at Interface.encodeFunctionData (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@ethersproject/abi/src.ts/interface.ts:378:18)
    at getInitializerData (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@openzeppelin/hardhat-upgrades/src/utils/initializer-data.ts:17:30)
    at Proxy.deployProxy (/Users/xdamman/github/citizenwallet/smartcontracts/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:48:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/xdamman/github/citizenwallet/smartcontracts/scripts/deploy-community-entrypoint.ts:77:21) {
  reason: 'types/values length mismatch',
  code: 'INVALID_ARGUMENT',
  count: { types: 1, values: 0 },
  value: { types: [ [ParamType] ], values: [] }
}
Error: Command failed: HARDHAT_NETWORK=base_testnet COMMUNITY_TOKEN_ADDRESS=0x1D02836fE4938005d4daa602B93b4fAC719Fa261 npx hardhat run ./scripts/deploy-community-entrypoint.ts
```

**Comment by xdamman** [comment]
I see that you made a commit that changed the signature of the profile creation: https://github.com/citizenwallet/smartcontracts/commit/81233679d2deb94532e11211c330b561953c0f7e#

That's the issue. 

So the question is: who should be the owner of that profile contract? The sponsor address? Or `process.env.DEPLOYER_ADDRESS` ?

**Comment by xdamman** [comment]
It worked, but now running into another similar issue:

```
⚙️ deploying AccountFactory...
Error: too many arguments:  in Contract constructor (count=2, expectedCount=0, code=UNEXPECTED_ARGUMENT, version=contracts/5.7.0)
```

This comes from this commit: https://github.com/citizenwallet/smartcontracts/commit/5d036e78928188dd7f17e8e163b21337d7d4abc1#diff-28238a4edcb0d982110b0c52b71c15e192da6f8439aa242e278ea1bea6f8da81

Not sure to understand. It looks like you removed the two arguments and moved them to an initializer. 
Does that mean that it is now using a proxy which wasn't the case before? I also see a `AccountFactoryFactory` which is quite confusing 🤯 

How am I supposed to update this code to make it work?
https://github.com/citizenwallet/smartcontracts/blob/d98c1ab51d7526c65702e84edc6954ed30be709c/scripts/deploy-community-entrypoint.ts#L155-L160

**Comment by xdamman** [comment]
I've been trying this but it doesn't work:

```js
const accountFactory = await ethers.getContractFactory("AccountFactory");
    accFactory = await upgrades.deployProxy(accountFactory, [], {
      kind: "uups",
      initializer: "initialize",
      constructorArgs: [process.env.ENTRYPOINT_ADDR, tokenEntryPoint.address],
      timeout: 999999,
    });
```

**Comment by xdamman** [comment]
Related PR: https://github.com/citizenwallet/smartcontracts/issues/18
